# Generated by Django 2.2.12 on 2021-05-23 08:22

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('instructions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='correctQ1',
            field=otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='correctQ2',
            field=otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='correctQ3',
            field=otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='correctQ4',
            field=otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='correctQ5',
            field=otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True, null=True),
        ),
    ]
