# Generated by Django 2.2.12 on 2021-04-29 15:09

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('instructions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='player',
            name='name',
        ),
        migrations.AddField(
            model_name='player',
            name='etudes',
            field=otree.db.models.StringField(choices=[('Sans diplôme', 'Sans diplôme'), ('Brevet des collèges, BEPC', 'Brevet des collèges, BEPC'), ('CAP, BEP', 'CAP, BEP'), ('Baccalaureat', 'Baccalaureat'), ('Bac +2 (DUT, BTS, DEUG)', 'Bac +2 (DUT, BTS, DEUG)'), ("Diplome de l'enseignement supérieur", "Diplome de l'enseignement supérieur")], max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='genre',
            field=otree.db.models.StringField(choices=[('Homme', 'Homme'), ('Femme', 'Femme'), ('Autre', 'Autre')], max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='age',
            field=otree.db.models.StringField(choices=[('15-17 ans', '15-17 ans'), ('18-24 ans', '18-24 ans'), ('25-34 ans', '25-34 ans'), (' 35-49 ans', ' 35-49 ans'), ('50-64 ans', '50-64 ans'), ('Plus de 65 ans', 'Plus de 65 ans')], max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='answerQ1',
            field=otree.db.models.FloatField(null=True, verbose_name='Quel est votre gain si vous achetez le quatirème produit ?'),
        ),
        migrations.AlterField(
            model_name='player',
            name='answerQ2',
            field=otree.db.models.FloatField(null=True, verbose_name="Quel est le gain le plus élevé que vous puissiez obtenir avec l'un des produits disponibles ?"),
        ),
        migrations.AlterField(
            model_name='player',
            name='answerQ3',
            field=otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], null=True, verbose_name="Y a-t-il une relation entre l'ordre dans lequel les produits apparaissent à l'écran et la recommandation ?"),
        ),
        migrations.AlterField(
            model_name='player',
            name='answerQ4',
            field=otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], null=True, verbose_name="A la première étape, la recommandation était vraiment mauvaise. Est-ce que cela veut dire qu'elle le sera également à toutes les étapes suivantes ?"),
        ),
        migrations.AlterField(
            model_name='player',
            name='answerQ5',
            field=otree.db.models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], null=True, verbose_name="Si à deux étapes différentes j'ai le choix entre exactement les mêmes produits, est-ce que la recommandation sera la même les deux fois ?"),
        ),
    ]
