# Generated by Django 2.2.12 on 2021-04-29 15:11

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('instructions', '0002_auto_20210429_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='etudes',
            field=otree.db.models.StringField(choices=[('Sans diplôme', 'Sans diplôme'), ('Brevet des collèges, BEPC', 'Brevet des collèges, BEPC'), ('CAP, BEP', 'CAP, BEP'), ('Baccalaureat', 'Baccalaureat'), ('Bac +2 (DUT, BTS, DEUG)', 'Bac +2 (DUT, BTS, DEUG)'), ("Diplôme de l'enseignement supérieur", "Diplôme de l'enseignement supérieur")], max_length=10000, null=True),
        ),
    ]
