# Generated by Django 2.2.12 on 2021-04-29 15:14

from django.db import migrations
import otree.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('conclusion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='feedback',
            field=otree.db.models.LongStringField(null=True, verbose_name="N'hésitez pas à nous décrire ci-dessous votre ressenti par rapport à l'expérience "),
        ),
    ]
